/**
 * Earthpoints API
 * Earthpoints API description
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ClientCredentialsResponseDto model module.
 * @module model/ClientCredentialsResponseDto
 * @version 0.1
 */
class ClientCredentialsResponseDto {
    /**
     * Constructs a new <code>ClientCredentialsResponseDto</code>.
     * @alias module:model/ClientCredentialsResponseDto
     * @param accessToken {String} 
     * @param expiresIn {Number} 
     * @param tokenType {String} 
     */
    constructor(accessToken, expiresIn, tokenType) { 
        
        ClientCredentialsResponseDto.initialize(this, accessToken, expiresIn, tokenType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, accessToken, expiresIn, tokenType) { 
        obj['access_token'] = accessToken;
        obj['expires_in'] = expiresIn;
        obj['token_type'] = tokenType;
    }

    /**
     * Constructs a <code>ClientCredentialsResponseDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ClientCredentialsResponseDto} obj Optional instance to populate.
     * @return {module:model/ClientCredentialsResponseDto} The populated <code>ClientCredentialsResponseDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ClientCredentialsResponseDto();

            if (data.hasOwnProperty('access_token')) {
                obj['access_token'] = ApiClient.convertToType(data['access_token'], 'String');
            }
            if (data.hasOwnProperty('expires_in')) {
                obj['expires_in'] = ApiClient.convertToType(data['expires_in'], 'Number');
            }
            if (data.hasOwnProperty('token_type')) {
                obj['token_type'] = ApiClient.convertToType(data['token_type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} access_token
 */
ClientCredentialsResponseDto.prototype['access_token'] = undefined;

/**
 * @member {Number} expires_in
 */
ClientCredentialsResponseDto.prototype['expires_in'] = undefined;

/**
 * @member {String} token_type
 */
ClientCredentialsResponseDto.prototype['token_type'] = undefined;






export default ClientCredentialsResponseDto;

