/**
 * Earthpoints API
 * Earthpoints API description
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ClientCredentialsDto model module.
 * @module model/ClientCredentialsDto
 * @version 0.1
 */
class ClientCredentialsDto {
    /**
     * Constructs a new <code>ClientCredentialsDto</code>.
     * @alias module:model/ClientCredentialsDto
     * @param clientId {String} 
     * @param clientSecret {String} 
     */
    constructor(clientId, clientSecret) { 
        
        ClientCredentialsDto.initialize(this, clientId, clientSecret);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, clientId, clientSecret) { 
        obj['client_id'] = clientId;
        obj['client_secret'] = clientSecret;
    }

    /**
     * Constructs a <code>ClientCredentialsDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ClientCredentialsDto} obj Optional instance to populate.
     * @return {module:model/ClientCredentialsDto} The populated <code>ClientCredentialsDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ClientCredentialsDto();

            if (data.hasOwnProperty('client_id')) {
                obj['client_id'] = ApiClient.convertToType(data['client_id'], 'String');
            }
            if (data.hasOwnProperty('client_secret')) {
                obj['client_secret'] = ApiClient.convertToType(data['client_secret'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} client_id
 */
ClientCredentialsDto.prototype['client_id'] = undefined;

/**
 * @member {String} client_secret
 */
ClientCredentialsDto.prototype['client_secret'] = undefined;






export default ClientCredentialsDto;

