/**
 * Earthpoints API
 * Earthpoints API description
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PointEvent from './PointEvent';

/**
 * The CreatePointEventResponseDto model module.
 * @module model/CreatePointEventResponseDto
 * @version 0.1
 */
class CreatePointEventResponseDto {
    /**
     * Constructs a new <code>CreatePointEventResponseDto</code>.
     * @alias module:model/CreatePointEventResponseDto
     * @param msg {String} 
     * @param event {module:model/PointEvent} 
     * @param userTotalPoints {Number} 
     */
    constructor(msg, event, userTotalPoints) { 
        
        CreatePointEventResponseDto.initialize(this, msg, event, userTotalPoints);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, msg, event, userTotalPoints) { 
        obj['msg'] = msg;
        obj['event'] = event;
        obj['userTotalPoints'] = userTotalPoints;
    }

    /**
     * Constructs a <code>CreatePointEventResponseDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreatePointEventResponseDto} obj Optional instance to populate.
     * @return {module:model/CreatePointEventResponseDto} The populated <code>CreatePointEventResponseDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreatePointEventResponseDto();

            if (data.hasOwnProperty('msg')) {
                obj['msg'] = ApiClient.convertToType(data['msg'], 'String');
            }
            if (data.hasOwnProperty('event')) {
                obj['event'] = PointEvent.constructFromObject(data['event']);
            }
            if (data.hasOwnProperty('userTotalPoints')) {
                obj['userTotalPoints'] = ApiClient.convertToType(data['userTotalPoints'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} msg
 */
CreatePointEventResponseDto.prototype['msg'] = undefined;

/**
 * @member {module:model/PointEvent} event
 */
CreatePointEventResponseDto.prototype['event'] = undefined;

/**
 * @member {Number} userTotalPoints
 */
CreatePointEventResponseDto.prototype['userTotalPoints'] = undefined;






export default CreatePointEventResponseDto;

