/**
 * Earthpoints API
 * Earthpoints API description
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PointEvent model module.
 * @module model/PointEvent
 * @version 0.1
 */
class PointEvent {
    /**
     * Constructs a new <code>PointEvent</code>.
     * @alias module:model/PointEvent
     * @param hash {String} 
     * @param userid {String} 
     * @param isBurn {Boolean} 
     * @param points {Number} 
     * @param message {String} 
     * @param verb {String} 
     * @param platform {String} 
     * @param icon {String} 
     * @param timestamp {Date} 
     * @param metadata {Object} 
     */
    constructor(hash, userid, isBurn, points, message, verb, platform, icon, timestamp, metadata) { 
        
        PointEvent.initialize(this, hash, userid, isBurn, points, message, verb, platform, icon, timestamp, metadata);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, hash, userid, isBurn, points, message, verb, platform, icon, timestamp, metadata) { 
        obj['hash'] = hash;
        obj['userid'] = userid;
        obj['isBurn'] = isBurn;
        obj['points'] = points;
        obj['message'] = message;
        obj['verb'] = verb;
        obj['platform'] = platform;
        obj['icon'] = icon;
        obj['timestamp'] = timestamp;
        obj['metadata'] = metadata;
    }

    /**
     * Constructs a <code>PointEvent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PointEvent} obj Optional instance to populate.
     * @return {module:model/PointEvent} The populated <code>PointEvent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PointEvent();

            if (data.hasOwnProperty('hash')) {
                obj['hash'] = ApiClient.convertToType(data['hash'], 'String');
            }
            if (data.hasOwnProperty('userid')) {
                obj['userid'] = ApiClient.convertToType(data['userid'], 'String');
            }
            if (data.hasOwnProperty('isBurn')) {
                obj['isBurn'] = ApiClient.convertToType(data['isBurn'], 'Boolean');
            }
            if (data.hasOwnProperty('points')) {
                obj['points'] = ApiClient.convertToType(data['points'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('verb')) {
                obj['verb'] = ApiClient.convertToType(data['verb'], 'String');
            }
            if (data.hasOwnProperty('platform')) {
                obj['platform'] = ApiClient.convertToType(data['platform'], 'String');
            }
            if (data.hasOwnProperty('icon')) {
                obj['icon'] = ApiClient.convertToType(data['icon'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {String} hash
 */
PointEvent.prototype['hash'] = undefined;

/**
 * @member {String} userid
 */
PointEvent.prototype['userid'] = undefined;

/**
 * @member {Boolean} isBurn
 */
PointEvent.prototype['isBurn'] = undefined;

/**
 * @member {Number} points
 */
PointEvent.prototype['points'] = undefined;

/**
 * @member {String} message
 */
PointEvent.prototype['message'] = undefined;

/**
 * @member {String} verb
 */
PointEvent.prototype['verb'] = undefined;

/**
 * @member {String} platform
 */
PointEvent.prototype['platform'] = undefined;

/**
 * @member {String} icon
 */
PointEvent.prototype['icon'] = undefined;

/**
 * @member {Date} timestamp
 */
PointEvent.prototype['timestamp'] = undefined;

/**
 * @member {Object} metadata
 */
PointEvent.prototype['metadata'] = undefined;






export default PointEvent;

