/**
 * Earthpoints API
 * Earthpoints API description
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The User model module.
 * @module model/User
 * @version 0.1
 */
class User {
    /**
     * Constructs a new <code>User</code>.
     * @alias module:model/User
     * @param userid {String} 
     * @param firstName {String} 
     * @param email {String} 
     * @param emails {Array.<String>} 
     * @param timezone {String} 
     * @param createdAt {Date} 
     * @param events {Array.<String>} 
     * @param connections {Array.<String>} 
     * @param points {Number} 
     * @param lastEmailed {Date} 
     */
    constructor(userid, firstName, email, emails, timezone, createdAt, events, connections, points, lastEmailed) { 
        
        User.initialize(this, userid, firstName, email, emails, timezone, createdAt, events, connections, points, lastEmailed);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, userid, firstName, email, emails, timezone, createdAt, events, connections, points, lastEmailed) { 
        obj['userid'] = userid;
        obj['firstName'] = firstName;
        obj['email'] = email;
        obj['emails'] = emails;
        obj['timezone'] = timezone;
        obj['createdAt'] = createdAt;
        obj['events'] = events;
        obj['connections'] = connections;
        obj['points'] = points;
        obj['lastEmailed'] = lastEmailed;
    }

    /**
     * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/User} obj Optional instance to populate.
     * @return {module:model/User} The populated <code>User</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new User();

            if (data.hasOwnProperty('userid')) {
                obj['userid'] = ApiClient.convertToType(data['userid'], 'String');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('emails')) {
                obj['emails'] = ApiClient.convertToType(data['emails'], ['String']);
            }
            if (data.hasOwnProperty('timezone')) {
                obj['timezone'] = ApiClient.convertToType(data['timezone'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('events')) {
                obj['events'] = ApiClient.convertToType(data['events'], ['String']);
            }
            if (data.hasOwnProperty('connections')) {
                obj['connections'] = ApiClient.convertToType(data['connections'], ['String']);
            }
            if (data.hasOwnProperty('points')) {
                obj['points'] = ApiClient.convertToType(data['points'], 'Number');
            }
            if (data.hasOwnProperty('lastEmailed')) {
                obj['lastEmailed'] = ApiClient.convertToType(data['lastEmailed'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} userid
 */
User.prototype['userid'] = undefined;

/**
 * @member {String} firstName
 */
User.prototype['firstName'] = undefined;

/**
 * @member {String} email
 */
User.prototype['email'] = undefined;

/**
 * @member {Array.<String>} emails
 */
User.prototype['emails'] = undefined;

/**
 * @member {String} timezone
 */
User.prototype['timezone'] = undefined;

/**
 * @member {Date} createdAt
 */
User.prototype['createdAt'] = undefined;

/**
 * @member {Array.<String>} events
 */
User.prototype['events'] = undefined;

/**
 * @member {Array.<String>} connections
 */
User.prototype['connections'] = undefined;

/**
 * @member {Number} points
 */
User.prototype['points'] = undefined;

/**
 * @member {Date} lastEmailed
 */
User.prototype['lastEmailed'] = undefined;






export default User;

