/**
 * Earthpoints API
 * Earthpoints API description
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EarthpointsApi);
  }
}(this, function(expect, EarthpointsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EarthpointsApi.CreatePlatformConnectionDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreatePlatformConnectionDto', function() {
    it('should create an instance of CreatePlatformConnectionDto', function() {
      // uncomment below and update the code to test CreatePlatformConnectionDto
      //var instance = new EarthpointsApi.CreatePlatformConnectionDto();
      //expect(instance).to.be.a(EarthpointsApi.CreatePlatformConnectionDto);
    });

    it('should have the property userid (base name: "userid")', function() {
      // uncomment below and update the code to test the property userid
      //var instance = new EarthpointsApi.CreatePlatformConnectionDto();
      //expect(instance).to.be();
    });

    it('should have the property profileId (base name: "profile_id")', function() {
      // uncomment below and update the code to test the property profileId
      //var instance = new EarthpointsApi.CreatePlatformConnectionDto();
      //expect(instance).to.be();
    });

    it('should have the property platform (base name: "platform")', function() {
      // uncomment below and update the code to test the property platform
      //var instance = new EarthpointsApi.CreatePlatformConnectionDto();
      //expect(instance).to.be();
    });

    it('should have the property emails (base name: "emails")', function() {
      // uncomment below and update the code to test the property emails
      //var instance = new EarthpointsApi.CreatePlatformConnectionDto();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new EarthpointsApi.CreatePlatformConnectionDto();
      //expect(instance).to.be();
    });

    it('should have the property phone (base name: "phone")', function() {
      // uncomment below and update the code to test the property phone
      //var instance = new EarthpointsApi.CreatePlatformConnectionDto();
      //expect(instance).to.be();
    });

    it('should have the property authToken (base name: "auth_token")', function() {
      // uncomment below and update the code to test the property authToken
      //var instance = new EarthpointsApi.CreatePlatformConnectionDto();
      //expect(instance).to.be();
    });

    it('should have the property tokenSecret (base name: "token_secret")', function() {
      // uncomment below and update the code to test the property tokenSecret
      //var instance = new EarthpointsApi.CreatePlatformConnectionDto();
      //expect(instance).to.be();
    });

    it('should have the property authExpiration (base name: "auth_expiration")', function() {
      // uncomment below and update the code to test the property authExpiration
      //var instance = new EarthpointsApi.CreatePlatformConnectionDto();
      //expect(instance).to.be();
    });

  });

}));
